### ISSUE TITLE
Appearance enhancement

### ISSUE THREAD

**Issue by rondvb** [ClevrSolutions/dynamic-data-grid#1]
Could you add a selection to make the Dynamic Data Grid Compact (like is possible in the DataGrid2?

**Comment by Andries-Smit** [comment]
@rondvb Can you please elaborate a bit more on your feature request?
Are you referring to data view listen to data grid? 
Or
Selection on one or multiple rows for button actions?
Currently now a workaround for selection can be used; by click events, linking to context and conditional classes

**Comment by Andries-Smit** [comment]
@rondvb styling properties in the widget results in CSS classes, you can use the same classes on the Dynamic Data Grid too.
Just add 'table-compact', 'table-striped' and or 'table-hover' to the Appearance common class

**Comment by FatalBlowSmokeShinobi420** [comment]
Hi Andries. Fantastic work! Do you by chance have a later version of the downloadable project available? I noticed that the downloaded demo is different than the hosted demo project at the bottom of the README. I am particularly interested in your implementation of the "Sample Access" page with the editable grid. 

Thank you!
