### ISSUE TITLE
Row Column Header

### ISSUE THREAD

**Issue by AbeBothma** [ClevrSolutions/dynamic-data-grid#5]
Hello Andries

Would it be possible to also allow for custom content in the Row Column Header section?

Kind regards

![Screenshot 2024-01-17 125233](https://github.com/ClevrSolutions/dynamic-data-grid/assets/114724772/131569e3-9284-49b6-ac3e-133cd0fb0531)

**Comment by Andries-Smit** [comment]
yes you can with the new 1.1.0 release
![image](https://github.com/ClevrSolutions/dynamic-data-grid/assets/6724749/ed4a335b-5e4c-4c38-9797-c8a528c8d709)
